project:
  type: website
  output-dir: docs

website:
  title: "Quinn-Lynas's-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: Portfolio_Project.qmd
        text: "Portfolio Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

