project:
  type: website
  output-dir: docs

website:
  title: "Quinn-Lynas's-Portfolio"
  navbar:
    background: primary
    search: true
    left:
     - text: "Home"
       href: index.qmd
     - text: "About"
       href: about.qmd
     - sidebar:class_projects
     - sidebar:research_projects
        
  sidebar:
    - id: class_projects
      title: "Class Projects"
      style: "docked"
      background: light
      contents: 
        - data_viz_final.qmd
        - Portfolio_Project.qmd
        - proof_portfolio.qmd
    - id: research_projects
      title: "Research Projects"
      style: "docked"
      background: light
      contents:
        - summer_uroc.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

